version: "3.9"

volumes:
  caddy_data:
  caddy_config:
  tasks_database:

networks:
  default:
    name: tc-network

services:
  proxy-server:
    image: caddy:2.3.0-alpine
    container_name: tc-proxy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
# <!!! Specify path to the Caddyfile (based on where you cloned the repository)
      - "/d/text-captcha-mag/api/Caddyfile:/etc/caddy/Caddyfile"
# !!!>
      - "caddy_data:/data"
      - "caddy_config:/config"

  ner-process-text:
    image: rsdo-ds3-ner-api:v1
    container_name: tc-ner-process-text
#    ports:
#      - "5000:5000"
    environment:
      NER_MODEL_PATH: "/app/data/models/bert_based/"
    volumes:
      - type: "bind"
# <!!! Specify path to the NER model
        source: "/d/text-captcha-mag/process/models/bert-base-multilingual-cased-bsnlp-2021-finetuned-5-epochs/"
# !!!>
        target: "/app/data/models/bert_based/"
        read_only: true

  classla-process-text:
    image: text-captcha-classla
    container_name: tc-classla-process-text
#    ports:
#      - "5010:5010"

  tasks-db:
    image: postgres
    container_name: tc-tasks-db
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_USER: "captcha3000"
      POSTGRES_PASSWORD: "=gxn9*fMi9xR<Sbp,3Zw"
    volumes:
      - tasks_database:/var/lib/postgresql

  text-ingest:
    image: text-captcha-text-ingest
    container_name: tc-text-ingest
#    ports:
#      - "8010:8010"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"

  task-manager:
    image: text-captcha-task-manager
    container_name: tc-task-manager
#    ports:
#      - "8020:8020"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"

  integration-demo:
    image: text-captcha-integration-demo
    container_name: tc-integration-demo
    restart: unless-stopped
#    ports:
#      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"