server:
  port: 8080
  servlet:
    context-path: /captcha

spring:
  datasource:
    url: jdbc:postgresql://tc-tasks-db:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: tasks12
  flyway:
    baseline-on-migrate: false
    schemas: public
    default-schema: public
    create-schemas: true

task-manager:
  ner-api: http://tc-ner-process-text:5000