server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:jpadb
    driver-class-name: org.h2.Driver
    username: root
    password: root12

task-manager:
  ner-api: http://tc-ner-process-text:5000