server:
  port: 8080
  servlet:
    context-path: /captcha

spring:
  datasource:
    url: jdbc:postgresql://tasks_db:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: tasks12

task-manager:
  ner-api: http://tc-ner-process-text:5000