server:
  servlet:
    context-path: /captcha/i
spring:
  datasource:
    url: jdbc:postgresql://tc-tasks-db:5432/postgres?currentSchema=captcha2
    driver-class-name: org.postgresql.Driver
    username: "captcha3000"
    password: "=gxn9*fMi9xR<Sbp,3Zw"
  jpa:
    database: postgresql
  flyway:
    baseline-on-migrate: false
    schemas: captcha2
    default-schema: captcha2
    create-schemas: true

task-manager:
  ner-api: http://tc-ner-process-text:5000
  classla-api: http://tc-classla-process-text:5010