server:
  servlet:
    context-path: /captcha/i
spring:
  datasource:
    url: jdbc:postgresql://tc-tasks-db:5432/postgres?currentSchema=captcha
    driver-class-name: org.postgresql.Driver
    username: "captcha3000"
    password: "=gxn9*fMi9xR<Sbp,3Zw"
  jpa:
    database: postgresql
  flyway:
    baseline-on-migrate: false
    schemas: captcha
    default-schema: captcha
    create-schemas: true

task-manager:
  ner-api: http://tc-ner-process-text:5000