server:
  servlet:
    context-path: /
spring:
#  datasource:
#    url: jdbc:h2:mem:jpadb
#    driver-class-name: org.h2.Driver
#    username: root
#    password: root12
  datasource:
    url: jdbc:postgresql://192.168.99.101:5432/postgres?currentSchema=captcha_proto
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "demo"
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
#    properties:
#      javax.persistence.schema-generation.scripts:
#        action: create
#        create-target: create.sql
#        create-source: metadata
  flyway:
    enabled: false
    baseline-on-migrate: true
    schemas: captcha_proto
    default-schema: captcha_proto
    create-schemas: true

text-ingest:
  ner-url: https://nlp.cebular.net/ner # http://192.168.99.101:5000
  classla-url: https://nlp.cebular.net/classla # http://localhost:5010
  coref-url: https://nlp.cebular.net/coref # http://localhost:5020