spring:
  datasource:
    url: jdbc:postgresql://192.168.99.101:5432/postgres?currentSchema=captcha
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: tasks12
  jpa:
    database: postgresql