server:
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.101:5432/postgres?currentSchema=captcha_proto
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "demo"
  jpa:
    database: postgresql
    show-sql: false